config/routes.rb
RiakRailsAuthentication::Application.routes.draw do
  
  root :to => 'sessions#new'
  resources :users
  resources :sessions, :only => [:new, :create] do
    delete 'destroy', :on => :collection
  end

end

app/models/basic_model.rb
module BasicModel
  extend ActiveSupport::Concern
  include ActiveAttr::BasicModel
  include ActiveAttr::Attributes
  include ActiveAttr::MassAssignment
  include ActiveModel::MassAssignmentSecurity
  include ActiveModel::ForbiddenAttributesProtection

end

app/models/user.rb
class User
  include BasicModel
  INDEX = ['email_bin', 'joined_int']

  #Doesn't make a lot of sense for range index but only for string/bin index
  INDEX.each do |index|
    define_singleton_method :"find_by_#{index.split('_').first}" do |value|
      bucket = riak_client[self.name.downcase.pluralize]
      bucket.get_index(index, value).map { |u| parse_from_riak(bucket[u]) }.first
    end
  end
  
  attribute :id
  attribute :name
  attribute :email
  attribute :password


  validates :email, presence: true

  #TODO all this method can/must be moved into BasicModel
  def store
    client = riak_client
    self.id ||= give_uuid
    user = client[self.class.name.downcase.pluralize].get_or_new(self.id)
    user.data = self.attributes
    user.indexes['email_bin'] << self.email
    user.indexes['joined_int'] << Time.now.utc.to_i
    #TODO it would be nice/necessary to pass a block to configure the bucket property before store
    user.store
  end

  def save
    valid? ? store : false
  end

  def destroy
    bucket = riak_client[self.name.downcase.pluralize]
    user = bucket.exist?(id) ? parse_from_riak(bucket[id]) : nil
    user ? user.delete : nil
  end

  def authenticate(password)
    #DO NOT USE IN PRODUCTION
    password == self.password
  end

  #Class Methods
  class << self
    def all(parse = true)
      client = riak_client
      bucket = client[self.name.downcase.pluralize]
      users = bucket.get_index('joined_int', 0..Time.now.utc.to_i)
      parse ? users.map { |u| parse_from_riak(bucket[u]) } : users
    end

    #RObject should be handled only in models, controller must see only Ruby object
    def parse_from_riak(rkobject)
      new(rkobject.data)
    end

    def find_by_id(id)
      bucket = riak_client[self.name.downcase.pluralize]
      bucket.exist?(id) ? parse_from_riak(bucket[id]) : nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

    def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def authenticate_user!
      redirect_to root_path, notice: 'You Must login' unless current_user
    end

  helper_method :current_user, :authenticate_user!
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    respond_to do |format|

      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        format.html { redirect_to users_url, :notice => "Logged in!" }
        format.json { render :json => {:response => 'Unauthorized !'} }
      else
        flash.now.alert = "Invalid email or password"
        format.html { render "new" }
        format.json { render :json => {:response => 'Unauthorized !'}, :status => 401 }
      end

    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  protected

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:danger, :info, :success, :warning, :alert]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success #if type == :notice
      # type = :danger   if [:error, :alert].include? type
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RiakRailsAuthentication</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= bootstrap_flash %>

<%= link_to 'Logout', sessions_path, :method => :delete if current_user %>


<%= yield %>

</body>
</html>

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.password_field :password
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
= session.inspect
%h1 Listing users

%table
  %tr
    %th Email
    %th Name
    %th Password
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.name
      %td= user.password
      %td
        = link_to 'Show', user_path(user.id)
        = link_to 'Destroy', user_path(user.id), :method => :delete, :confirm => 'Are you sure?'

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b Name:
  = @user.name
%p
  %b Password:
  = @user.password

= link_to 'Back', users_path